trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

# Some container definitions
resources:
 containers:
   - container: linux_1604
     image: ubuntu:16.04

jobs:
- job: JobWithContainers
  container: linux_1604
  continueOnError: false
  
  steps:
  - bash: |
      echo "hello world!"
