pool:
  vmImage: ubuntu-latest

trigger:
  - main

pr:
  - main

variables:
  BIN_OUTPUT_NAME: xqtr

jobs:
  - job: PushJob
    displayName: Push Job
    condition: ne(variables['Build.Reason'], 'PullRequest')
    continueOnError: false
    
    steps:
      - task: GoTool@0
        displayName:  Install GO
        inputs:
          version: '1.16'
      - task: SonarCloudPrepare@1
        displayName: Prepare Analysis on SonarCloud
        inputs:
          SonarCloud: 'ipeternella-personal-token'
          organization: 'igp'
          scannerMode: 'CLI'
          configMode: 'file'
          extraProperties: |
            sonar.projectKey=$(SONAR_PROJECT_KEY)
            sonar.host.url=https://sonarcloud.io
      - task: Go@0
        inputs:
          command: 'build'
          arguments: '-o $(Build.ArtifactStagingDirectory)/xqtr $(Build.SourcesDirectory)/cmd/xqtr/*.go'
      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'ipeternella-personal-azuredevops-token'
          repositoryName: '$(Build.Repository.Name)'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'gitTag'
          title: 'xqtR bin'
          releaseNotesSource: 'inline'
          releaseNotesInline: |
            # xqtR (executoR)
            
            This release contains the compiled binary of the xqtR command line tool which can be used by users.
          assets: '$(Build.ArtifactStagingDirectory)/xqtr'
          changeLogCompareToRelease: 'lastFullRelease'
          changeLogType: 'commitBased'

  - job: PullRequestJob
    displayName: Pull Request Job
    condition: eq(variables['Build.Reason'], 'PullRequest')
    continueOnError: false

    steps: 
      - task: GoTool@0
        displayName:  Install GO
        inputs:
          version: '1.16'
      - task: SonarCloudPrepare@1
        displayName: Prepare Analysis on SonarCloud
        inputs:
          SonarCloud: 'ipeternella-personal-token'
          organization: 'igp'
          scannerMode: 'CLI'
          configMode: 'file'
          extraProperties: |
            sonar.projectKey=$(SONAR_PROJECT_KEY)
            sonar.host.url=https://sonarcloud.io
      - task: Go@0
        displayName: Runs tests with coverage
        inputs:
          command: 'test'
          arguments: './... -coverprofile=coverage.out'
      - task: SonarCloudAnalyze@1
        displayName: Run Code Analysis