# --- External resources --- #
resources:
 containers:
   - container: linux_1604
     image: ubuntu:16.04

pool:
  vmImage: ubuntu-latest

# --- Triggers --- #
trigger:
- main

pr:
- main

# --- Jobs --- #
jobs:
- job: PushRequests
  condition: ne(variables['Build.Reason'], 'PullRequest')
  container: linux_1604
  continueOnError: false
  
  steps:
  - bash: |
      echo "Hi from a push!"
  - task: GoTool@0
    inputs:
      version: '1.16'

- job: PullRequests
  condition: eq(variables['Build.Reason'], 'PullRequest')
  container: linux_1604
  continueOnError: false

  steps:
  - bash: |
      echo "Hi from a PR!"
  - task: GoTool@0
    displayName:  Install GO
    inputs:
      version: '1.16'
  - task: Go@0
    displayName: Runs GO version
    inputs:
      command: 'custom'
      customCommand: 'version'
  - task: SonarCloudPrepare@1
    displayName: Prepare Analysis on SonarCloud
    inputs:
      SonarCloud: 'ipeternella-personal-token'
      organization: 'igp'
      scannerMode: 'CLI'
      configMode: 'file'
      extraProperties: |
        sonar.projectKey=$(SONAR_PROJECT_KEY)
        sonar.host.url=https://sonarcloud.io
  - task: Go@0
    displayName: Runs tests with coverage
    inputs:
      command: 'test'
      arguments: './... -coverprofile=coverage.out'
  - task: SonarCloudAnalyze@1
    displayName: Run Code Analysis