jobs:
  - title: installing software providers...
    steps:
      - name: brew update
        run: brew update

  - title: uninstall software...
    continue_on_error: true
    steps:
      - name: brew uninstall httpie
        run: brew uninstall httpie
      - name: brew uninstall lynx
        run: brew uninstall lynx
      - name: brew uninstall opera
        run: brew uninstall opera

  - title: install apps with software providers...
    steps:
      - name: install httpie
        run: brew install httpie
      - name: install lynx
        run: brew install lynx
      - name: install opera
        run: brew install --cask opera
