jobs:
  - title: installing software providers...
    steps:
      - name: brew update
        run: brew update

  - title: install apps with software providers...
    num_workers: 2
    steps:
      - name: install httpie
        run: brew install httpie
      - name: install lynx (terminal browser)
        run: brew install lynx
